### ISSUE TITLE
Create automated functional tests (using Reqnroll) to verify Weevil's software requirements.

### ISSUE THREAD

**Issue by Pressacco** [BlueDotBrigade/weevil#191]
# HowTo: Write Gherkin Scenarios

## Scenario Titles

There isn't a single "one-size-fits-all" approach to naming Gherkin scenarios, but there are best practices that can make scenarios more understandable and maintainable. These practices aim to make the scenario name descriptive enough to understand its purpose at a glance while being concise enough to be easily digestible. Here are some guidelines:

- **Clarity Over Brevity**: The name should make it immediately clear what the scenario is testing. While brevity is desired, it should not come at the expense of clarity.
- **Domain Language**: Use the language that the team and stakeholders understand. Domain-Specific Language (DSL) can be very effective here.
- **Outcome-Oriented**: Include the expected outcome or behavior in the scenario name to give a clear idea of what success looks like for the test.
- **Avoid Implementation Details**: Try not to include how the test will achieve its goal but rather focus on what you are trying to achieve.
- **Consistency**: Stick to a naming convention that the team agrees upon to make it easier to search for and understand scenarios.

Examples following these guidelines might look like:
- "Successful login with valid credentials"
- "Error on empty shopping cart checkout"
- "Admin access denied for regular users"
- "Open log file with valid format"
- "Error on opening corrupted log file"
# Lessons Learned

- Single Quote / Double Quote / Backtick text formatting works for...
   - GitHub : single & double quoted text
   - GitHub codespace: does not support syntax highlighting for Gherkin strings

# Relates To
- #362

# Articles

- [Powering your Cucumber Acceptance Tests with Jira Integration][JiraCucumberCodeGeneration]

[JiraCucumberCodeGeneration]: https://blogs.infomentum.com/powering-your-cucumber-acceptance-tests-with-jira-integration

**Comment by Pressacco** [comment]
Related to:
- #325

**Comment by Pressacco** [comment]
# Troubleshooting: DatenLokator Won't Run

Symptoms:

- _MS Test_ automated tests which include  _SpecFlow_ + _DatenLokator_ won't start via Visual Studio's _Test Explorer_.

Implementation Notes:

- If you _Debug_ a test you will discover that _MS Test_ does in fact start.  The problem is:
   - You cannot use _MS Test+'s `AssemblyInitialize` attribute in conjunction with SpecFlow's [test run hooks](hooks).
- Solution:
   1. Remove _MS Test+'s `AssemblyInitialize`.
   2. Use SpecFlow's [test run hooks](hooks) to initialize the [DatenLokator][] `v2.0.0` library.

[hooks]: https://docs.specflow.org/projects/specflow/en/latest/Bindings/Hooks.html
[DatenLokator]: https://www.nuget.org/packages/BlueDotBrigade.DatenLokator

**Comment by Pressacco** [comment]
# Challenges

## STA Thread

The `OpenAsync` Gherkin scenario is failing with a run-time error:
- `InvalidOperationException: The calling thread must be STA, because many UI components require this.`

With Just My Code disabled, you can see that the error is ultimately due to a .NET guard failing:

Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.VSInstallationUtilities.cs:
```CSharp
public static string? VSInstallPath
{   
   // ...
   // Use the Setup API to find the installation folder for currently running VS instance.
   if (new SetupConfiguration() is ISetupConfiguration setupConfiguration)
   {
      var currentConfiguration = setupConfiguration.GetInstanceForCurrentProcess();
      // ...
   } 
}
```

## Next Steps

- Is _Weevil_ really running UI for the MS Test... or is this simply a WPF guard that is being accidentally triggered?
- Solutions:
   1. Avoid calling the guard, or
   2. Run the functional test using a `STA Thread`

## Related Articles
- [MSTest v2: Customize test execution](https://www.meziantou.net/mstest-v2-customize-test-execution.htm)
   -  Talks about STA threads

**Comment by Pressacco** [comment]
# Problem: Unexpected SpecFlow Errors

## Symptoms
Visual Studio is displaying weird compiler errors & warnings
* `AndDiscoveryProviderSucceed: Error during binding discovery`
* `FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0`
* `JsonReaderException: Unexpected character encountered while parsing value`
* `AndDiscoveryProviderSucceed: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled.`

In Visual Studio:

* _Gherkin_ statements that clearly did not exist... were **not** being displayed as purple text in _Visual Studio_.

## Root Cause

* This problem appeared after upgrading projects to .Net Core 8

## Solution

* [Install the Visual Studio SpecFlow extension for .Net Core 8](https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.93-net8)

**Comment by Pressacco** [comment]
# Implementation

After porting from SpecFlow to Reqnroll, the run-time starting throwing the following exception because the dependency injection is slightly different with Reqnroll.

```
Solution:
* `BeforeTestRun` only accepts a `ITestRunnerManager` parameter
* `AfterTestRun` only accepts a `ITestRunnerManager` parameter


Problem: 

Reqnroll.BoDi.ObjectContainerException
  HResult=0x80131500
  Message=Interface cannot be resolved: Reqnroll.ITestRunner
  Source=Reqnroll
  StackTrace:
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath, TimeSpan timeout)
   at Reqnroll.BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at Reqnroll.BoDi.ObjectContainer.Resolve(Type typeToResolve, String name)
   at Reqnroll.Infrastructure.TestObjectResolver.ResolveBindingInstance(Type bindingType, IObjectContainer container)
   at Reqnroll.Infrastructure.TestExecutionEngine.ResolveArgument(IObjectContainer container, IBindingParameter parameter)
   at Reqnroll.Infrastructure.TestExecutionEngine.<>c__DisplayClass54_0.<ResolveArguments>b__0(IBindingParameter p)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Reqnroll.Infrastructure.TestExecutionEngine.ResolveArguments(IHookBinding hookBinding, IObjectContainer currentContainer)
   at Reqnroll.Infrastructure.TestExecutionEngine.<InvokeHookAsync>d__50.MoveNext()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext()
   at Reqnroll.Infrastructure.TestExecutionEngine.<FireEventsAsync>d__48.MoveNext()
   at Reqnroll.Infrastructure.TestExecutionEngine.<OnTestRunStartAsync>d__32.MoveNext()
   at Reqnroll.TestRunner.<OnTestRunStartAsync>d__10.MoveNext()
   at Reqnroll.TestRunnerManager.<FireTestRunStartAsync>d__35.MoveNext()
   at Reqnroll.TestRunnerManager.<OnTestRunStartAsync>d__46.MoveNext()
   at BlueDotBrigade_Weevil_MSTestAssemblyHooks.<AssemblyInitializeAsync>d__0.MoveNext() in C:\Code\BlueDotBrigade\OpenSource\weevil\Tst\BlueDotBrigade.Weevil.Core-FunctionalTests\obj\x64\Debug\net8.0\MSTest.AssemblyHooks.cs:line 25

  This exception was originally thrown at this call stack:
    [External Code]
    BlueDotBrigade_Weevil_MSTestAssemblyHooks.AssemblyInitializeAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext) in MSTest.AssemblyHooks.cs
```

**Comment by Pressacco** [comment]
# Status Update

While the improvements could be made, for the most part this _user story_ has been implemented.

`Closing`
